version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./psql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mysecretpassword

  app:
    image: ruby:2.3-jessie
    command: bin/start
    ports:
      - "443:3000"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - RAILS_ENV=development
      - DB_HOST=db
      - DB_PASSWORD=mysecretpassword
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    depends_on:
      - db
